# Generated by Django 3.2 on 2023-06-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeNumber',
            field=models.IntegerField(null=True),
        ),
    ]
